/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Dimension;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Fábio
 */
public class Card extends javax.swing.JFrame {
    
    LocalDate dataAtual = LocalDate.now();
    DateTimeFormatter formatador = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    String dataAtualFormatada = dataAtual.format(formatador);

    /**
     * Creates new form Card
     * @param barbeiro
     * @param cliente
     * @param servico
     * @param data
     * @param hora
     * @param observacao
     * @param preco
     */
    public Card(String barbeiro, String cliente, String servico, String data, String hora, String observacao, String preco) {
        initComponents();
        
        clienteLabel.setText("Olá, " + cliente);
        dataLabel.setText(data);
        horaLabel.setText(hora + "h");
        barbeiroLabel.setText("Barbeiro: " + barbeiro);
        servicoLabel.setText("Serviço: " + servico);
        observacaoLabel.setText("Observação: " + observacao);
        precoLabel.setText("R$" + preco + ",00");
        dataCriacaoLabel.setText("Criado em: " + dataAtualFormatada);
        validadeLabel.setText("Validade: " + data);
    }

    private Card() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
    
    private void imprimir() {
        PrinterJob job = PrinterJob.getPrinterJob();

        job.setPrintable((graphics, pageFormat, pageIndex) -> {
            if (pageIndex > 0) {
                return Printable.NO_SUCH_PAGE;
            }

            // Obtém o tamanho da tela do JFrame
            Dimension size = getContentPane().getSize();

            // Desenha a tela no gráfico
            getContentPane().print(graphics);

            // Retorna que a página foi impressa com sucesso
            return Printable.PAGE_EXISTS;
        });

        // Mostra a janela de diálogo para o usuário selecionar as opções de impressão
        if (job.printDialog()) {
            try {
                // Chama o método print para imprimir a tela
                job.print();
            } catch (PrinterException ex) {
                ex.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dataCriacaoLabel = new javax.swing.JLabel();
        validadeLabel = new javax.swing.JLabel();
        precoLabel = new javax.swing.JLabel();
        observacaoLabel = new javax.swing.JLabel();
        servicoLabel = new javax.swing.JLabel();
        barbeiroLabel = new javax.swing.JLabel();
        horaLabel = new javax.swing.JLabel();
        dataLabel = new javax.swing.JLabel();
        clienteLabel = new javax.swing.JLabel();
        botaoImprimir = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(9, 9, 11));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dataCriacaoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dataCriacaoLabel.setForeground(new java.awt.Color(255, 255, 255));
        dataCriacaoLabel.setText("<Criacao>");
        jPanel1.add(dataCriacaoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 170, -1));

        validadeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        validadeLabel.setForeground(new java.awt.Color(255, 255, 255));
        validadeLabel.setText("<Validade>");
        jPanel1.add(validadeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 170, -1));

        precoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        precoLabel.setForeground(new java.awt.Color(255, 255, 255));
        precoLabel.setText("R$");
        jPanel1.add(precoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 170, -1));

        observacaoLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        observacaoLabel.setForeground(new java.awt.Color(255, 255, 255));
        observacaoLabel.setText("Observacao: <Obs>");
        observacaoLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(observacaoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 360, 80));

        servicoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        servicoLabel.setForeground(new java.awt.Color(255, 255, 255));
        servicoLabel.setText("Serviço: <Serviço>");
        jPanel1.add(servicoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 360, -1));

        barbeiroLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        barbeiroLabel.setForeground(new java.awt.Color(255, 255, 255));
        barbeiroLabel.setText("Barbeiro: <Barbeiro>");
        jPanel1.add(barbeiroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 360, -1));

        horaLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        horaLabel.setForeground(new java.awt.Color(255, 255, 255));
        horaLabel.setText("<Hora>");
        jPanel1.add(horaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 160, -1));

        dataLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dataLabel.setForeground(new java.awt.Color(255, 255, 255));
        dataLabel.setText("<Data>");
        jPanel1.add(dataLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 160, -1));

        clienteLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clienteLabel.setForeground(new java.awt.Color(255, 255, 255));
        clienteLabel.setText("Olá, <Usuário>");
        jPanel1.add(clienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 350, -1));

        botaoImprimir.setText("Imprimir");
        botaoImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(botaoImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, -1, -1));

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Card_1x.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoImprimirActionPerformed
        imprimir();
    }//GEN-LAST:event_botaoImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Card().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barbeiroLabel;
    private javax.swing.JButton botaoImprimir;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel clienteLabel;
    private javax.swing.JLabel dataCriacaoLabel;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JLabel horaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel observacaoLabel;
    private javax.swing.JLabel precoLabel;
    private javax.swing.JLabel servicoLabel;
    private javax.swing.JLabel validadeLabel;
    // End of variables declaration//GEN-END:variables
}
