/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;

/**
 *
 * @author Fábio
 */
public class Finanças extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Finanças() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        LogoutIcon = new javax.swing.JLabel();
        MenuText = new javax.swing.JLabel();
        ProfileIcon = new javax.swing.JLabel();
        Profile = new javax.swing.JTextField();
        MySchedule = new javax.swing.JTextField();
        NewScheduleButton = new javax.swing.JTextField();
        Logo = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        SidebarBackground = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Javanese Text", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Finanças");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, 60));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 380, 30));

        jLabel28.setFont(new java.awt.Font("Javanese Text", 1, 28)); // NOI18N
        jLabel28.setText("Total:");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 50));

        jLabel29.setFont(new java.awt.Font("Javanese Text", 0, 22)); // NOI18N
        jLabel29.setText("R$ 150,00");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, 60));

        jLabel30.setFont(new java.awt.Font("Javanese Text", 1, 18)); // NOI18N
        jLabel30.setText("Matheus Messias");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 60));

        jLabel31.setFont(new java.awt.Font("Javanese Text", 0, 22)); // NOI18N
        jLabel31.setText("R$ 50,00");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, 60));

        jLabel32.setFont(new java.awt.Font("Javanese Text", 1, 18)); // NOI18N
        jLabel32.setText("Matheus Messias");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 60));
        jPanel6.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 380, 30));

        jLabel33.setFont(new java.awt.Font("Javanese Text", 1, 18)); // NOI18N
        jLabel33.setText("Matheus Messias");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 60));

        jLabel34.setFont(new java.awt.Font("Javanese Text", 0, 22)); // NOI18N
        jLabel34.setText("R$ 50,00");
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, 60));
        jPanel6.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 380, 30));

        jLabel35.setFont(new java.awt.Font("Javanese Text", 1, 28)); // NOI18N
        jLabel35.setText("Pendências");
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, 60));

        jLabel36.setFont(new java.awt.Font("Javanese Text", 0, 22)); // NOI18N
        jLabel36.setText("R$ 50,00");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, 60));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 420, 310));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Javanese Text", 1, 28)); // NOI18N
        jLabel8.setText("Lucros:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 60));

        jLabel18.setFont(new java.awt.Font("Javanese Text", 0, 22)); // NOI18N
        jLabel18.setText("R$ 5.840");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, 60));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 380, 30));

        jLabel20.setFont(new java.awt.Font("Javanese Text", 1, 28)); // NOI18N
        jLabel20.setText("Saldo:");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 60));

        jLabel21.setFont(new java.awt.Font("Javanese Text", 0, 22)); // NOI18N
        jLabel21.setText("R$ 9.640");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, 60));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 380, 30));

        jLabel22.setFont(new java.awt.Font("Javanese Text", 1, 28)); // NOI18N
        jLabel22.setText("Despesas:");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 60));

        jLabel23.setFont(new java.awt.Font("Javanese Text", 0, 22)); // NOI18N
        jLabel23.setText("R$ 3.800");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, 60));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 420, 200));

        LogoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout-icon.png"))); // NOI18N
        jPanel1.add(LogoutIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, -1, -1));

        MenuText.setBackground(new java.awt.Color(255, 255, 255));
        MenuText.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        MenuText.setForeground(new java.awt.Color(255, 255, 255));
        MenuText.setText("Menu");
        jPanel1.add(MenuText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        ProfileIcon.setForeground(new java.awt.Color(153, 153, 153));
        ProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-button-icon.png"))); // NOI18N
        ProfileIcon.setText("Profile");
        jPanel1.add(ProfileIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 40, -1));

        Profile.setEditable(false);
        Profile.setBackground(new java.awt.Color(9, 9, 10));
        Profile.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Profile.setForeground(new java.awt.Color(141, 141, 153));
        Profile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Profile.setText("Yuri Assunção");
        Profile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(9, 9, 10), 12, true));
        Profile.setCaretColor(new java.awt.Color(9, 9, 10));
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });
        jPanel1.add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 190, 50));

        MySchedule.setEditable(false);
        MySchedule.setBackground(new java.awt.Color(9, 9, 10));
        MySchedule.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        MySchedule.setForeground(new java.awt.Color(255, 255, 255));
        MySchedule.setText("Meus Agendamentos");
        MySchedule.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(9, 9, 10), 12, true));
        MySchedule.setCaretColor(new java.awt.Color(9, 9, 10));
        MySchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyScheduleMouseClicked(evt);
            }
        });
        jPanel1.add(MySchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 220, 40));

        NewScheduleButton.setEditable(false);
        NewScheduleButton.setBackground(new java.awt.Color(9, 9, 10));
        NewScheduleButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        NewScheduleButton.setForeground(new java.awt.Color(255, 255, 255));
        NewScheduleButton.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NewScheduleButton.setText("Fazer um novo agendamento");
        NewScheduleButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(9, 9, 10), 12, true));
        NewScheduleButton.setCaretColor(new java.awt.Color(9, 9, 10));
        jPanel1.add(NewScheduleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 220, 40));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-small.png"))); // NOI18N
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        Background.setBackground(new java.awt.Color(66, 66, 71));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 0, -1, -1));

        SidebarBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sidebar.png"))); // NOI18N
        jPanel1.add(SidebarBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 286, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 700, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 981, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfileActionPerformed

    private void MyScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyScheduleMouseClicked
        
    }//GEN-LAST:event_MyScheduleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finanças.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finanças.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finanças.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finanças.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finanças().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel LogoutIcon;
    private javax.swing.JLabel MenuText;
    private javax.swing.JTextField MySchedule;
    private javax.swing.JTextField NewScheduleButton;
    private javax.swing.JTextField Profile;
    private javax.swing.JLabel ProfileIcon;
    private javax.swing.JLabel SidebarBackground;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
